apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-mongo
  labels:
    app: demo-mongo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1G
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-mongo
  labels:
    app: demo-mongo
spec:
  selector:
    matchLabels:
      app: demo-mongo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: demo-mongo
    spec:
      containers:
      - image: mongo:5
        name: mongo
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: demo-mongo
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: demo-mongo
              key: password
        ports:
        - containerPort: 27017
          name: demo-mongo
        volumeMounts:
        - name: demo-mongo
          mountPath: /data
      volumes:
      - name: demo-mongo
        persistentVolumeClaim:
          claimName: demo-mongo
---
apiVersion: v1
kind: Service
metadata:
  name: demo-mongo
  labels:
    app: demo-mongo
spec:
  ports:
  - port: 27017
  selector:
    app: demo-mongo
---
apiVersion: v1
kind: Secret
metadata:
  name: demo-mongo 
  labels:
    app: demo-mongo
stringData:
  username: demo
  password: demo

