apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-db
  labels:
    app: demo-db
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1G
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-db
  labels:
    app: demo-db
spec:
  selector:
    matchLabels:
      app: demo-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: demo-db
    spec:
      initContainers:
      - name: remove-lost-found
        image: busybox
        command:          
        - sh
        - -c
        - |
          rm -fr /var/lib/postgresql/data/lost+found
        volumeMounts:
        - name: demo-db
          mountPath: /var/lib/postgresql/data
      containers:
      - image: postgres:11
        name: postgres
        env:
        - name: POSTGRES_INITDB_ARGS
          value: "--encoding=UTF-8 --locale=C"
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: demo-db
              key: postgres-db
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: demo-db
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: demo-db
              key: postgres-password
        ports:
        - containerPort: 5432
          name: demo-db
        volumeMounts:
        - name: demo-db
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: demo-db
        persistentVolumeClaim:
          claimName: demo-db
---
apiVersion: v1
kind: Service
metadata:
  name: demo-db
  labels:
    app: demo-db
spec:
  ports:
  - port: 5432
  selector:
    app: demo-db
---
apiVersion: v1
kind: Secret
metadata:
  name: demo-db 
  labels:
    app: demo-db
stringData:
  postgres-user: demo
  postgres-password: demo
  postgres-db: demo

